TARGET_ARCH = linux 
#SYSTEMC = $(SYSTEMC)
INCDIR = -I. -I.. -I$(SYSTEMC)/include
LIBDIR = -L. -L.. -L$(SYSTEMC)/lib-$(TARGET_ARCH)
LIBS   =  -lsystemc -lm $(EXTRA_LIBS)

CXXFLAGS=-Wall -DDEBUG_BUILD -DNO_STORAGE -DUSE_SYSTEM_C_INTERFACE=1 -DUSE_SCIC_MEMSYS_QUERY=1 #-DUSE_DEBUG_SYSTEMC#-D_SIM_ 
OPTFLAGS=-O3 
DEBUG=1

ifdef DEBUG
ifeq ($(DEBUG), 1)
OPTFLAGS= -O0 -g
endif
endif
CXXFLAGS+=$(OPTFLAGS)

EXE_NAME=DRAMSim
LIB_NAME=libdramsim.so

SRC = $(wildcard *.cpp)
OBJ = $(addsuffix .o, $(basename $(SRC)))

#build portable objects (i.e. with -fPIC)
POBJ = $(addsuffix .po, $(basename $(SRC)))

REBUILDABLES=$(OBJ) ${POBJ} $(EXE_NAME) $(LIB_NAME) 

all: ${EXE_NAME}

#   $@ target name, $^ target deps, $< matched pattern

$(EXE_NAME): $(OBJ)
	$(CXX) $(CXXFLAGS) $(INCDIR) $(LIBDIR) -o $@ $^ $(LIBS)
	@echo "Built $@ successfully" 

$(LIB_NAME): $(POBJ)
	g++ -g -shared -Wl,-soname,$@ -o $@ $^
	@echo "Built $@ successfully"

#include the autogenerated dependency files for each .o file
-include $(OBJ:.o=.dep)
-include $(POBJ:.po=.dep)

# build dependency list via gcc -M and save to a .dep file
%.dep : %.cpp
	@$(CXX) -M $(CXXFLAGS) $(INCDIR) $(LIBDIR) $< > $@

# build all .cpp files to .o files
%.o : %.cpp
	g++ $(CXXFLAGS) $(INCDIR) $(LIBDIR) -o $@ $(LIBS)  -c $<

#po = portable object .. for lack of a better term
%.po : %.cpp
	g++ $(CXXFLAGS) -DLOG_OUTPUT -fPIC -o $@ -c $<

clean: 
	-rm -f $(REBUILDABLES) *.dep
